# ===================================================================
# Spring Boot configuration for using the local MySQL database
#
# This configuration only applies the local MySQL settings. 
# It is used in combination with the existing application*.yml files.
# This config requires MySQL to be installed on your computer or on a server!
# ===================================================================

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/moviemanager?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: dev
    password: dev
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
