spring:
  application:
    name: Java Training Exercise 4
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:file:./target/database/data
    username: dba
    password: mypassword01